version: '3.9'

services:
  mysql:
    container_name: sakura_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_videos
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - sakura_network
networks:
  sakura_network: